hf:
  dataDir: ../data
  fileNameFormat: "{prefix}-{index}.zst"
  timestampsFileNamePrefix: timestamps
  valuesFileNamePrefix: values
  
  compress:
    outBufferSize: 64
    compressionLevel: 0
    
  decompress:
