hf:
  dataDir: ../data
  fileNameFormat: "{prefix}-{index}.zst"
  timestampsFileNamePrefix: timestamps
  valuesFileNamePrefix: values
  zstFileMaxSize: 1024
  compress:
    bufferSize: 4096
    compressionLevel: 0
  decompress:
