hf:
  dataDir: ../data
  filenameFormat: "{prefix}---{index}"
  timestampFileNamePrefix: timestamps
  valuesFileNamePrefix: values
  zstFileMaxSize: 1024
  compress:
    bufferSize: 4096
    compressionLevel: 0
  decompress:
