hf:
  dataDir: data
  jsonDir: data
  fileNameFormat: "{prefix}-{index}"
  timestampsFileNamePrefix: timestamps
  valuesFileNamePrefix: values
  
  compress:
    outBufferSize: 40960
    compressionLevel: 0
